name: wp-deployer-native
type: wordpress
docroot: web
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false

hooks:
    post-start:
        - exec: /var/www/html/.ddev/commands/web/composer-install-if-needed
        - exec: /var/www/html/.ddev/commands/web/import-seed
        - exec: /var/www/html/.ddev/commands/web/import-uploads
        - exec: /var/www/html/.ddev/commands/web/install-wp-if-needed